# train val data
train: ../train_data/images/train_mini
val: ../train_data/images/val_mini

# クラス数
nc: 6

# クラス名
#names: ['要補修-1.区画線','要補修-2.道路標識','要補修-3.照明','補修不要-1.区画線','補修不要-2.道路標識','補修不要-3.照明']
names: ['補修不要-1.区画線','要補修-1.区画線','補修不要-2.道路標識','要補修-2.道路標識','補修不要-3.照明','要補修-3.照明']